# Form implementation generated from reading ui file 'presentation/screens/CrearCuenta.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 299)
        Dialog.setStyleSheet("background-color: #1e1e1e;\n"
"font-family: Segoe UI, Arial;")
        self.btnCodMonedaIngresar = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.btnCodMonedaIngresar.setGeometry(QtCore.QRect(40, 200, 291, 51))
        self.btnCodMonedaIngresar.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #777777;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #555555;\n"
"}")
        self.btnCodMonedaIngresar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnCodMonedaIngresar.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnCodMonedaIngresar.setObjectName("btnCodMonedaIngresar")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 60, 186, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"background-color: transparent;\n"
"border: none;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineCodMonedaIngresar = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineCodMonedaIngresar.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    border: 2px solid #404040;\n"
"    border-radius: 6px;\n"
"    padding: 12px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    selection-background-color: #404040;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #666666;\n"
"    background-color: #252525;\n"
"}")
        self.lineCodMonedaIngresar.setObjectName("lineCodMonedaIngresar")
        self.verticalLayout.addWidget(self.lineCodMonedaIngresar)

        self.retranslateUi(Dialog)
        self.btnCodMonedaIngresar.accepted.connect(Dialog.accept) # type: ignore
        self.btnCodMonedaIngresar.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Ingrese código de moneda:"))
