# Form implementation generated from reading ui file 'presentation/screens/login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(565, 392)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: Segoe UI, Arial;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 120, 291, 156))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNameUser = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblNameUser.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.lblNameUser.setObjectName("lblNameUser")
        self.verticalLayout.addWidget(self.lblNameUser)
        self.lineNameUser = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineNameUser.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    border: 2px solid #404040;\n"
"    border-radius: 6px;\n"
"    padding: 12px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    selection-background-color: #404040;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #666666;\n"
"    background-color: #252525;\n"
"}")
        self.lineNameUser.setText("")
        self.lineNameUser.setObjectName("lineNameUser")
        self.verticalLayout.addWidget(self.lineNameUser)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineContra = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineContra.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    border: 2px solid #404040;\n"
"    border-radius: 6px;\n"
"    padding: 12px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    selection-background-color: #404040;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #666666;\n"
"    background-color: #252525;\n"
"}\n"
"")
        self.lineContra.setText("")
        self.lineContra.setObjectName("lineContra")
        self.verticalLayout.addWidget(self.lineContra)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 290, 288, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnIngresar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnIngresar.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnIngresar.setObjectName("btnIngresar")
        self.horizontalLayout.addWidget(self.btnIngresar)
        self.btnRegistro = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnRegistro.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #777777;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #555555;\n"
"}")
        self.btnRegistro.setObjectName("btnRegistro")
        self.horizontalLayout.addWidget(self.btnRegistro)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(220, 40, 101, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblNameUser.setText(_translate("Form", "Nombre de usuario:"))
        self.label.setText(_translate("Form", "Contraseña:"))
        self.btnIngresar.setText(_translate("Form", "Ingresar"))
        self.btnRegistro.setText(_translate("Form", "Registro"))
        self.label_2.setText(_translate("Form", "Bienvenido/a"))
