# Form implementation generated from reading ui file 'presentation/screens/menuTransacciones.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 413)
        MainWindow.setStyleSheet("background-color: #1e1e1e;\n"
"font-family: Segoe UI, Arial;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblmenu = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblmenu.setGeometry(QtCore.QRect(120, 40, 261, 16))
        self.lblmenu.setStyleSheet("color: #ffffff;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"background-color: transparent;\n"
"border: none;")
        self.lblmenu.setObjectName("lblmenu")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 70, 160, 290))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCrearCuenta = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnCrearCuenta.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnCrearCuenta.setObjectName("btnCrearCuenta")
        self.verticalLayout.addWidget(self.btnCrearCuenta)
        self.btnDepositar = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnDepositar.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnDepositar.setObjectName("btnDepositar")
        self.verticalLayout.addWidget(self.btnDepositar)
        self.btnComprar = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnComprar.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnComprar.setObjectName("btnComprar")
        self.verticalLayout.addWidget(self.btnComprar)
        self.btnVender = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnVender.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnVender.setObjectName("btnVender")
        self.verticalLayout.addWidget(self.btnVender)
        self.btnCuentas = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnCuentas.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnCuentas.setObjectName("btnCuentas")
        self.verticalLayout.addWidget(self.btnCuentas)
        self.btnSalir = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnSalir.setStyleSheet("QPushButton {\n"
"    background-color: #404040;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #555555;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #333333;\n"
"}")
        self.btnSalir.setObjectName("btnSalir")
        self.verticalLayout.addWidget(self.btnSalir)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblmenu.setText(_translate("MainWindow", "Bienvenido al menu de transacciones"))
        self.btnCrearCuenta.setText(_translate("MainWindow", "Crear cuenta"))
        self.btnDepositar.setText(_translate("MainWindow", "Depositar ARS"))
        self.btnComprar.setText(_translate("MainWindow", "Comprar Moneda"))
        self.btnVender.setText(_translate("MainWindow", "Vender Moneda"))
        self.btnCuentas.setText(_translate("MainWindow", "Ver Monedas"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
