# Form implementation generated from reading ui file 'presentation/screens/register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 200, 241, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRegistrarse = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnRegistrarse.setObjectName("btnRegistrarse")
        self.horizontalLayout.addWidget(self.btnRegistrarse)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 40, 241, 146))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNameUserReg = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblNameUserReg.setObjectName("lblNameUserReg")
        self.verticalLayout.addWidget(self.lblNameUserReg)
        self.lineNameUserReg = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineNameUserReg.setText("")
        self.lineNameUserReg.setObjectName("lineNameUserReg")
        self.verticalLayout.addWidget(self.lineNameUserReg)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineContraReg = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineContraReg.setText("")
        self.lineContraReg.setObjectName("lineContraReg")
        self.verticalLayout.addWidget(self.lineContraReg)
        self.lblContra2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblContra2.setObjectName("lblContra2")
        self.verticalLayout.addWidget(self.lblContra2)
        self.lineContraReg2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineContraReg2.setText("")
        self.lineContraReg2.setObjectName("lineContraReg2")
        self.verticalLayout.addWidget(self.lineContraReg2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnRegistrarse.setText(_translate("Form", "Registro"))
        self.lblNameUserReg.setText(_translate("Form", "Nombre de usuario:"))
        self.label.setText(_translate("Form", "Contraseña:"))
        self.lblContra2.setText(_translate("Form", "Reingrese la contraseña:"))
