# Form implementation generated from reading ui file 'presentation/screens/VenderMoneda.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: Segoe UI, Arial;\n"
"}")
        self.btnVender = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.btnVender.setGeometry(QtCore.QRect(60, 230, 291, 41))
        self.btnVender.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #777777;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #555555;\n"
"}")
        self.btnVender.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnVender.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnVender.setObjectName("btnVender")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 40, 211, 156))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNameUser = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblNameUser.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.lblNameUser.setObjectName("lblNameUser")
        self.verticalLayout.addWidget(self.lblNameUser)
        self.lineMonedaVender = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineMonedaVender.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    border: 2px solid #404040;\n"
"    border-radius: 6px;\n"
"    padding: 12px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    selection-background-color: #404040;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #666666;\n"
"    background-color: #252525;\n"
"}")
        self.lineMonedaVender.setText("")
        self.lineMonedaVender.setObjectName("lineMonedaVender")
        self.verticalLayout.addWidget(self.lineMonedaVender)
        self.lblNameUser_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblNameUser_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.lblNameUser_2.setObjectName("lblNameUser_2")
        self.verticalLayout.addWidget(self.lblNameUser_2)
        self.lineMonedaVender_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineMonedaVender_2.setStyleSheet("QLineEdit {\n"
"    background-color: #2d2d2d;\n"
"    border: 2px solid #404040;\n"
"    border-radius: 6px;\n"
"    padding: 12px;\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    selection-background-color: #404040;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #666666;\n"
"    background-color: #252525;\n"
"}")
        self.lineMonedaVender_2.setText("")
        self.lineMonedaVender_2.setObjectName("lineMonedaVender_2")
        self.verticalLayout.addWidget(self.lineMonedaVender_2)

        self.retranslateUi(Dialog)
        self.btnVender.accepted.connect(Dialog.accept) # type: ignore
        self.btnVender.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblNameUser.setText(_translate("Dialog", "Moneda a vender:"))
        self.lblNameUser_2.setText(_translate("Dialog", "Monto a vender:"))
