# Form implementation generated from reading ui file 'presentation/screens/VerCuentas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: Segoe UI, Arial;\n"
"}")
        self.tableCuentas = QtWidgets.QTableWidget(parent=Dialog)
        self.tableCuentas.setGeometry(QtCore.QRect(90, 20, 201, 201))
        self.tableCuentas.setStyleSheet("QTableWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #d4d4d4;\n"
"    font-size: 13px;\n"
"    border: none;\n"
"    gridline-color: #404040;\n"
"    alternate-background-color: #252525;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #2d2d2d;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #264f78;\n"
"    color: white;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #333333;\n"
"    color: #d4d4d4;\n"
"    border: none;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget QScrollBar:vertical {\n"
"    background-color: #2d2d2d;\n"
"    width: 15px;\n"
"}\n"
"QTableWidget QScrollBar:horizontal {\n"
"    background-color: #2d2d2d;\n"
"    height: 15px;\n"
"}\n"
"QTableWidget QScrollBar::handle:vertical {\n"
"    background-color: #404040;\n"
"    border-radius: 7px;\n"
"}\n"
"QTableWidget QScrollBar::handle:horizontal {\n"
"    background-color: #404040;\n"
"    border-radius: 7px;\n"
"}\n"
"QTableWidget QScrollBar::handle:vertical:hover,\n"
"QTableWidget QScrollBar::handle:horizontal:hover {\n"
"    background-color: #555555;\n"
"}")
        self.tableCuentas.setObjectName("tableCuentas")
        self.tableCuentas.setColumnCount(2)
        self.tableCuentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCuentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCuentas.setHorizontalHeaderItem(1, item)
        self.btnSalir = QtWidgets.QPushButton(parent=Dialog)
        self.btnSalir.setGeometry(QtCore.QRect(90, 240, 201, 51))
        self.btnSalir.setStyleSheet("QPushButton {\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    min-width: 100px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #777777;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #555555;\n"
"}")
        self.btnSalir.setObjectName("btnSalir")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableCuentas.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Moneda"))
        item = self.tableCuentas.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Saldo"))
        self.btnSalir.setText(_translate("Dialog", "Salir"))
